export default {
  'string': 'string',
  'number': 'number',
  'boolean': 'boolean',
  'undefined': 'undefined',
  'null': 'null',
  'array': 'array',
  'object': 'object',
  //
  'should be': 'should be',
  'with value': 'with value',
  'must be': 'must be',
  'or': 'or',
  'greater than': 'greater than',
  'equal to': 'equal to',
  'less than': 'less than',
  'at least': 'at least',
  'length': 'length',
  'fails to match pattern': 'fails to match pattern',
  'characters long': 'characters long',
  'a date': 'a date',
  'a email': 'a email',
  'a url': 'a url',
}