export default {
  'string': '字符串',
  'number': '数字',
  'boolean': '布尔值',
  'undefined': '未定义',
  'null': '空值',
  'array': '数组',
  'object': '对象',
  //
  'should be': '应该是',
  'with value': '值为',
  'must be': '必须是',
  'or': '或者',
  'greater than': '大于',
  'equal to': '等于',
  'less than': '小于',
  'at least': '至少',
  'length': '长度',
  'fails to match pattern': '无法匹配',
  'characters long': '个字符',
  'a date': '有效日期',
  'a email': '有效邮箱',
  'a url': '有效网址',
}